version: 2.1
jobs:
  release:
    docker:
      - image: circleci/golang:1.16.5
    working_directory: /go/src/github.com/ory/k8s
    steps:
      - checkout
      - run: make release
      - run: git config --global user.email "aeneas@ory.sh"
      - run: git config --global user.name "aeneasr"
      - run: git checkout -b make-release HEAD
      - run: git add -A
      - run: git commit -a -m "Release $CIRCLE_TAG"
      - run: git push origin HEAD:master

  helm-docs:
    docker:
      - image: circleci/golang:1.16.5
    working_directory: /go/src/github.com/ory/k8s
    steps:
      - checkout
      - run:
          command: |
            curl -L https://github.com/norwoodj/helm-docs/releases/download/v1.5.0/helm-docs_1.5.0_Linux_x86_64.tar.gz -o helm-docs.tar.gz
            tar -xvf helm-docs.tar.gz
      - run: ./helm-docs -c helm/charts/
      - run: git config --global user.email "aeneas@ory.sh"
      - run: git config --global user.name "aeneasr"
      - run: git checkout -b regen-docs HEAD
      - run: git add helm/charts
      - run: git commit -m "Regenerate helm docs $(date)" || echo "No changes to commit"
      - run: git push origin HEAD:master

workflows:
  version: 2
  scheduled-workflow:
    triggers:
    - schedule:
        cron: "0 0 * * *"
        filters:
          branches:
            only:
            - master
    jobs:
    - helm-docs
  ci:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - upgrade:
          filters:
            tags:
              only: /.*/
      - lint:
          filters:
            tags:
              only: /.*/
      - validate:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - lint
            - validate
            - test
            - upgrade
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
