name: CI
on:
  push:
  pull_request:

jobs:

  dependencies:
    name: Prepare Dependencies
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Setup dependencies
        uses: ./.github/actions/deps-setup

  detect-repo-changes:
    name: Detected Repo Changes
    runs-on: ubuntu-20.04
    outputs:
      helms-changed: ${{ steps.changed_charts.outputs.matrix }}
      no-changes: ${{ steps.changed_charts.outputs.no_changes}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.9.1
        id: filter
        with:
          base: master
          # `-helm` suffix aims that we can easily filter helm charts
          filters: |
            hydra-helm:
              - 'helm/charts/hydra/**'
            hydra-maester-helm:
              - 'helm/charts/hydra-maester/**'
            keto-helm:
              - 'helm/charts/keto/**'
            kratos-helm:
              - 'helm/charts/kratos/**'
            kratos-selfservice-ui-node-helm:
              - 'helm/charts/kratos-selfservice-ui-node/**'
            oathkeeper-helm:
              - 'helm/charts/oathkeeper/**'
            oathkeeper-maester-helm:
              - 'helm/charts/oathkeeper-maester/**'
      # This step will take output from paths-filter and then process it in order to get what helm charts have been updated
      # It allows us to do matrix in validating & testing process
      - name: Generate helm chart matrix to be validated
        id: changed_charts
        env:
          FILTER_OUTPUT: ${{ toJson(steps.filter.outputs) }}
        run: |
           updated_charts=$(echo "$FILTER_OUTPUT" | jq -r 'to_entries | map(select((.key | endswith("-helm")) and .value == "true")) | map(.key)')
           updated_charts=$(echo "$updated_charts" | sed "s/-helm//g")

           if [[ "$updated_charts" == "[]" ]]; then 
            echo ::set-output name=no_changes::"true"
           fi
           echo ::set-output name=matrix::{\"chart\":$(echo $updated_charts)}\"
           
           echo "Charts array to run CI on: $updated_charts"
  
  check:
    name: Check Helm Chart ${{ matrix.chart || 'none' }}
    if: ${{ needs.detect-repo-changes.outputs.no-changes != 'true' }}
    needs: [dependencies, detect-repo-changes]
    runs-on: ubuntu-20.04
    env:
      HELM_CHART: ${{ matrix.chart }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installing kubeval
        run: helm plugin install https://github.com/instrumenta/helm-kubeval
      - name: Lint helm chart 
        run: make helm-lint
      - name: Validate helm chart 
        run: make helm-validate
    strategy:
      matrix: ${{ fromJson(needs.detect-repo-changes.outputs.helms-changed) }}

 
  test-upgrade:
    name: Upgrade Helm Chart '${{ matrix.chart || 'none' }}'
    if: ${{ needs.detect-repo-changes.outputs.no-changes != 'true' }}
    needs: [check, detect-repo-changes, dependencies]
    runs-on: ubuntu-20.04
    env:
      HELM_CHART: ${{ matrix.chart }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install k3d 
        run: |
          export PATH=".bin:$PATH"
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/v5.4.4/install.sh | USE_SUDO="false" K3D_INSTALL_DIR=".bin" bash
      - name: Test upgrade for helm chart 
        run: make helm-upgrade
    strategy:
      matrix: ${{ fromJson(needs.detect-repo-changes.outputs.helms-changed) }}
 
  test-install:
    name: Install Helm Chart '${{ matrix.chart || 'none' }}'
    if: ${{ needs.detect-repo-changes.outputs.no-changes != 'true' }}
    needs: [check, detect-repo-changes, dependencies]
    runs-on: ubuntu-20.04
    env:
      HELM_CHART: ${{ matrix.chart }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install k3d 
        run: |
          export PATH=".bin:$PATH"
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/v5.4.4/install.sh | USE_SUDO="false" K3D_INSTALL_DIR=".bin" bash
      - name: Test install for helm chart 
        run: make helm-test
    strategy:
      matrix: ${{ fromJson(needs.detect-repo-changes.outputs.helms-changed) }}

  release:
    name: Release
    if: ${{ github.ref_type == 'tag' }}
    needs: [test-install, test-upgrade]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Define current tag version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Generate documentation 
        run: |
            pushd .bin
            curl -L https://github.com/norwoodj/helm-docs/releases/download/v1.5.0/helm-docs_1.5.0_Linux_x86_64.tar.gz -o helm-docs.tar.gz
            tar -xvf helm-docs.tar.gz
            ./helm-docs -c ../helm/charts
            popd
      - name: Release helm charts
        run: make release
      - name: Push commit for release 
        run: |
          git config --global user.email "aeneas@ory.sh"
          git config --global user.name "aeneasr"
          git checkout -b make-release HEAD
          git add -A 
          git commit -a -m "Release ${RELEASE_VERSION}
          
          [skip ci]"

          git push origin HEAD:ci/migrate-gha